/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TugasBab3;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author ASUS
 */
public class GUI_PersewaanKamera extends JFrame {
    private JLabel label1, label2, label3, label4, label5;
    private JTextField field1, field2, field3, field4;
    private JTextArea area;
    private JButton button;
    

 
    public GUI_PersewaanKamera() {
        setTitle("Persewaan Kamera");
        setSize(400, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(6, 2));
        
        label1 = new JLabel("PERSEWAAN KAMERA");
        label2 = new JLabel("Jenis Kamera:");
        label3 = new JLabel("Harga Sewa:");
        label4 = new JLabel("Lama Sewa:");
        label5 = new JLabel("Total Biaya:");

        field1 = new JTextField();
        field2 = new JTextField();
        field3 = new JTextField();
        field4 = new JTextField();
        field4.setEditable(false);

        area = new JTextArea();
        JScrollPane scrollPane = new JScrollPane(area);

        button = new JButton("Hitung Biaya");

        panel.add(label1);
        panel.add(new JLabel(""));
        panel.add(label2);
        panel.add(field1);
        panel.add(label3);
        panel.add(field2);
        panel.add(label4);
        panel.add(field3);
        panel.add(label5);
        panel.add(field4);
        panel.add(button);
        panel.add(scrollPane);
        
        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String jenisKamera = field1.getText();
                int hargaSewa = Integer.parseInt(field2.getText());
                int lamaSewa = Integer.parseInt(field3.getText());
                
                KameraDigital kameraDigital = new KameraDigital(jenisKamera, hargaSewa, lamaSewa, 12);
                KameraAnalog kameraAnalog = new KameraAnalog(jenisKamera, hargaSewa / 2, lamaSewa, "35mm");

                int biayaDigital = kameraDigital.hitungBiaya();
                int biayaAnalog = kameraAnalog.hitungBiaya();
                int totalBiaya = biayaDigital + biayaAnalog;
                
                field4.setText(Integer.toString(totalBiaya));
                area.setText("Jenis Kamera: " + jenisKamera + "\nHarga Sewa: " + hargaSewa + "\nLama Sewa: " + lamaSewa + "\nTotal Biaya: " + totalBiaya);
            }
        });
        add(panel);
        setVisible(true);   
        }
    
    public static void main(String[] args) {
        new GUI_PersewaanKamera();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtJenisKamera = new javax.swing.JTextField();
        txtHargaSewa = new javax.swing.JTextField();
        txtLamaSewa = new javax.swing.JTextField();
        txtTotalBiaya = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Persewaan Kamera");

        jLabel2.setText("Jenis Kamera");

        jLabel3.setText("Harga Sewa");

        jLabel4.setText("Lama Sewa");

        jLabel5.setText("Total Biaya");

        btnHitung.setText("Hitung Biaya");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHitung)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(txtJenisKamera)
                            .addComponent(txtLamaSewa)
                            .addComponent(txtHargaSewa)
                            .addComponent(txtTotalBiaya, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                        .addGap(107, 107, 107))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtJenisKamera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHargaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLamaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnHitung)
                .addGap(124, 124, 124))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtHargaSewa;
    private javax.swing.JTextField txtJenisKamera;
    private javax.swing.JTextField txtLamaSewa;
    private javax.swing.JTextField txtTotalBiaya;
    // End of variables declaration//GEN-END:variables
}
